In [9]:
import numpy as np
import scipy as sc
from scipy.optimize import rosen, shgo, basinhopping, differential_evolution, dual_annealing

#print(np.__version__)
#print(sc.__version__)

### SHGO

In [7]:
bounds = [(0,2), (0, 2), (0, 2), (0, 2), (0, 2)]
result = shgo(rosen, bounds)
result.x, result.fun

(array([1., 1., 1., 1., 1.]), 2.920392374190081e-18)

In [9]:
def eggholder(x):
    return (-(x[1] + 47.0)* np.sin(np.sqrt(abs(x[0]/2.0 + (x[1] + 47.0))))- x[0] * np.sin(np.sqrt(abs(x[0] - (x[1] + 47.0)))))

bounds = [(-512, 512), (-512, 512)]


In [10]:
result = shgo(eggholder, bounds, n=30, sampling_method='sobol')

In [11]:
result.x, result.fun

(array([512.        , 404.23180542]), -959.6406627208505)

In [12]:
result.xl

array([[ 512.        ,  404.23180542],
       [ 283.07593402, -487.12566542],
       [-294.66820039, -462.01964031],
       [-105.87688985,  423.15324143],
       [-242.97923629,  274.38032063],
       [-506.25823477,    6.3131022 ],
       [-408.71981195, -156.10117154],
       [ 150.23210485,  301.31378508],
       [  91.00922754, -391.28375925],
       [ 202.8966344 , -269.38042147],
       [ 361.66625957, -106.96490692],
       [-219.40615102, -244.06022436],
       [ 151.59603137, -100.61082677]])

In [14]:
result.funl

array([-959.64066272, -718.16745962, -704.80659592, -565.99778097,
       -559.78685655, -557.36868733, -507.87385942, -493.9605115 ,
       -426.48799655, -421.15571437, -419.31194957, -410.98477763,
       -202.53912972])

### basinhopping

In [3]:
minimizer_kwargs = {"method":"L-BFGS-B"}
x0 = [0.0, 0.0, 0.0, 0.0]
result = basinhopping(rosen, x0, minimizer_kwargs=minimizer_kwargs, niter=200)
result.x, result.fun

(array([0.99999967, 0.99999933, 0.99999867, 0.99999733]),
 2.3415805813713422e-12)

### Differential Evolution

In [5]:
bounds = [(0,2), (0, 2), (0, 2), (0, 2), (0, 2)]
result = differential_evolution(rosen, bounds)
result.x, result.fun

(array([1., 1., 1., 1., 1.]), 0.0)

In [6]:
result = differential_evolution(rosen, bounds, updating='deferred', workers=2)
result.x, result.fun

(array([1., 1., 1., 1., 1.]), 0.0)

In [7]:
def ackley(x):
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e

In [8]:
bounds = [(-5, 5), (-5, 5)]
result = differential_evolution(ackley, bounds)
result.x, result.fun

(array([0., 0.]), 4.440892098500626e-16)

### Dual Annealing

In [10]:
func = lambda x: np.sum(x*x - 10*np.cos(2*np.pi*x)) + 10*np.size(x)
lw = [-5.12] * 10
up = [5.12] * 10
result = dual_annealing(func, bounds=list(zip(lw, up)), seed=1234)
print("global minimum: xmin = {0}, f(xmin) = {1:.6f}".format(result.x, result.fun))

global minimum: xmin = [-4.01437110e-09 -4.09453039e-09 -4.62324575e-09 -5.25566065e-09
 -5.21144691e-09 -3.54957375e-09 -3.60677746e-09 -3.02473237e-09
 -4.74921667e-09 -4.40927392e-09], f(xmin) = 0.000000
